# Generated by Django 5.1.1 on 2025-01-27 15:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0003_alter_booking_payment_method'),
    ]

    operations = [
        migrations.CreateModel(
            name='Citys',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='booking',
            name='payment_method',
            field=models.CharField(choices=[('Stripe', 'Stripe'), ('Stripe', 'Stripe')], default='None', max_length=50),
        ),
        migrations.CreateModel(
            name='Hoteis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='packages.citys')),
            ],
        ),
        migrations.CreateModel(
            name='HotelTarifa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('Categorie', models.CharField(choices=[('Standard', 'Standard'), ('Superior', 'Superior'), ('Luxo', 'Luxo')], max_length=50)),
                ('single', models.DecimalField(decimal_places=2, max_digits=10)),
                ('price_single', models.DecimalField(decimal_places=2, max_digits=10)),
                ('double', models.DecimalField(decimal_places=2, max_digits=10)),
                ('price_double', models.DecimalField(decimal_places=2, max_digits=10)),
                ('triple', models.DecimalField(decimal_places=2, max_digits=10)),
                ('price_triple', models.DecimalField(decimal_places=2, max_digits=10)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='packages.hoteis')),
            ],
        ),
    ]
